/*
使用下面函数生成20位随机字符作为key
const nanoid = (length = 20) => {
  const chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
  let result = chars[Math.floor(Math.random() * 26)] // 第一位为随机字母

  for (let i = 1; i < length; i++) {
    result += chars[Math.floor(Math.random() * chars.length)] // 其余位为随机字符
  }
  return result
}
*/

const arrs = [
  ['EMPTY', '-', '-'],
  ['APP_TITLE', ['预测性维护', 'Pre Maintenance']],
  ["ppsgVRDiON9PufdmmAyA", ["层级", "Level"]],
  ["hQo72Vl8W0ybN8z9jtnN", ["所有层级", "All levels"]],
  ["vlFshqQ11jo0Im0i6PHE", ["当前层级", "Current level"]],
  ["zjjQWeiaw4kBnHfgzPam", ["联网状态", "Network Status"]],
  ["hKkvGt24zcTqQDMkjvai", ["在线", "Online"]],
  ["p0P1gq6WJ6QboCnuxGSd", ["离线", "Offline"]],
  ["zL5hjUuMNMMqFw0LyUsG", ["设备列表", "Equipment List"]],
  ["gdxFfAK6XIYngqorHtUS", ["设备名", "Equipment Name"]],
  ["fM4f8YMGRF0HWapXEKmA", ["设备类型", "Equipment Type"]],
  ["hEBZnVg17ikCStS1Bmw3", ["物模型", "Model"]],
  ["gTGElTiHZ0fHol3IPvUr", ["设备Code", "Equipment Code"]],
  ["tgXVzqg4Gzq5u6ZFB1lb", ["父级Code", "Parent Code"]],
  ["l5cseH6drcOJPPLu0ztT", ["物类型/物模型", "Model Type / Model"]],
  ["fDnak8xGanmtfJH0EfjI", ["是", "Is"]],
  ["iEqpWj6xrSKNL3kFqBRY", ["关键设备", "Critical Asset"]],
  ["xuoW2b9Aaa24UtlZmMGm", ["设备类型", "Equip Type"]],
  ["wK7Y8bHdtauIp6val9Ao", ["运行状态", "Running Status"]],
  ["zCR3Xy3FrqbGZ50EufJR", ["是否启用", "Status"]],
  ['tjY4zsqJA49cLTpD1GO0', ['告警', 'Alarm']],
  ['jRHm3vWSGsMcZPzExD6M', ['正常', 'Normal']],
  ["dV9BDFVlPPhJtRE9Ky4p", ["关闭", "Close"]],
  ["fKatj4ZJfvf9BQWgS2mo", ["详情", "Details"]],
  ["eMdQDlNPlGkxmCdo4ZwJ", ["设备详情", "Equip Details"]],
  ["zx5NRcRK1wcWlasr2npP", ["信息", "Message"]],
  ["pt8vrdx4ApwMKednW9um", ["属性", "Property"]],
  ["d9773Zg5TwhBd8WoYvBy", ["关键属性", "Critical Property"]],
  ["jKaO6jNSg7fPFveSsVqy", ["暂无数据", "No Data"]],
  ["jKaO6jNSg7fPFveSsVqz", ["没有更多数据了", "No More Data"]],
  ["tyWEemuayX7RhDjUJdtx", ["设备消息统计", "Device message statistics"]],
  ["gxnlBNC627hyylJXapw1", ["设备流量统计", "Device traffic statistics"]],
  ["zDfxMDN8zhUBRWEsgNP1", ["总数", "Total"]],
  ["e7ufm3oZyCam5GXB5yz5", ["成功", "Success"]],
  ["dukuz3eIlzLE3oDB6SX3", ["总流量", "Total Flow"]],
  ["bDHaZEgfJnFgUykpfnF1", ["成功流量", "Succeeded Flow"]],
  ["dFGvvMYvmVXd13M7VYh0", ["基本信息", "Basic information"]],
  ["paa451bKAt04W81p0Msh", ["详情描述", "Remark"]],
  ["bL9XuYcUE0VXoO85av1g", ["列表", "List"]],
  ["dQqBEs0ufejtAzf6pD8E", ["名称", "Name"]],
  ["l2gckC4kb4VXNwr1M9zg", ["描述", "Description"]],
  ["yX0YltsWn8r0nGN8WIDg", ["属性数据类型", "DataType"]],
  ["pZrYykfEPVLuh8JPuzP3", ["更新时间", "UpdateTime"]],
  ["q032wfIndoysl28DuK8W", ["领域", "Field"]],
  ["tD2S2rwyI8ayJPS4m48I", ["值", "Value"]],
  ["qo0Yzi4wzN0zHpK3OsRH", ["标签", "Tag"]],
  ["irbUNxwsVY9Bs1EigGfm", ["时序图", "Timing Diagram"]],
  ["jLiakCvWgXr0cgfv7ADl", ["散点图", "Pot"]],
  ["faX8CuJskcgFKqSyRzFl", ["折线图", "Line"]],
  ["grQZQTLeeCqsIq0jJbCN", ["柱状图", "Bar"]],
  ["paJZV34CRAz83Way6FiV", ["直方图", "Histogram"]],
  ["fLVXohMtckOjG1kZxhiL", ["热力图", "Hot"]],
  ["euQd4QhxPOKBizcZSiTP", ["聚合时间", "Aggregation time"]],
  ["x5wUzLJI8dzhGFiZ0boN", ["聚合方式", "Aggregation method"]],
  ["dFsdnPr7Du6vTzkplGEv", ["模型名称", "Model Name"]],
  ["cRpunXetNtNu2zwC3RWF", ["模型类型", "Model Type"]],
  ["q3YDNa9U7iyCzjhBKX9K", ["模型状态", "Model Status"]],
  ["jsQiI3wJsxI4qHDRK9zs", ["触发部件", "Trigger Component"]],
  ["shU2YU6vHwsonlXhnUWX", ["模型", "Model"]],
  ["fKX2exkqFIhlxi8JGl0J", ["推理资源", "Model Resources"]],
  ["lM0XGncZWFPkDWH63BqE", ["边缘AI", "Edge AI"]],
  ["cg5wneH6hoLjMcr9Najs", ["云端Ai", "Cloud Ai"]],
  ["xgxjDl3wBTTaAjlVkZXm", ["运行配置", "Model Config"]],
  ["tFjBo2vopgj0CfEALJS6", ["事件触发", "Alarm Setting"]],
  ["poGP3yK22xcKc9swGECb", ["告警规则", "Alarm rule"]],
  ["naIVHsihIlHF4rCgfmb3", ["告警等级", "Alarm Level"]],
  ["wfnVmoagiQpP9FuiKMpA", ["级", "Level"]],
  ["ilQHaH6gJwBjBFFHBdI7", ["行动名称", "Action Name"]],
  ["so6ejP9wB7OR88OYFXO7", ["行动类型", "Action Type"]],
  ["aYE2TKjpzcMjFcZGhHym", ["执行方式", "Execution Method"]],
  ["gtfZ5kDSpgd1eoHhypnn", ["行动次数", "Action Count"]],
  ["dSewrNMY0oHPxAXtT8OT", ["编辑行动配置", "Edit Action Configuration"]],
  ["p0YBfKsBcjTzz2fUiOXX", ["行动调用记录", "Action Call Records"]],
  ["ty9BU3NpURwE9blfSFQB", ["调用时间", "Call Time"]],
  ["kZbJMrOMxSJfVXFGUMFx", ["触发类型", "Trigger Type"]],
  ["sBG8deXjEjtILb5IuDSj", ["行动结果", "Action Result"]],
  ["lUZwHcXn0Q1TotyduAT7", ["行动绑定", "Action binding"]],
  ["mWYe1V4wswtPgJCTWCE4", ["编辑", "Edit"]],
  ["mWYe1V4wswtPgJCTWCE5", ["保存", "Save"]],

  ['h8ohSygfiHJuKAFSfTv9', ['确定删除行动配置', 'Confirm to delete action']],
  ["uIZoCkSr8L50KfjaLWVu", ["请求类型", "Request Type"]],
  ["mxLEPdLnADtY0G6GgPH7", ["请求地址", "Request URL"]],
  ["oKgS7a2t6f08DrRPwbbK", ["请输入请求地址", "Enter Request URL"]],
  ["s8nz0kp6qGoiiFQUY9FI", ["认证", "Authentication"]],
  ["dkAbhGGJ5dNc3xUi1LoL", ["用户名", "Username"]],
  ["vRsjDcnN2zTiNhWJFriR", ["请输入登录用户名", "Enter Username"]],
  ["i0r0SS0h6AXaKV5Gxr9Q", ["密码", "Password"]],
  ["pYe9zHvRGYpBnCbNospf", ["请输入登录密码", "Enter Password"]],
  ["e7ZFyiyT7DNwbhAo5Amb", ["确认删除行动?", "Confirm Deletion of Action?"]],
  ["izrqy5viWsNfrxO4CCfQ", ["MQTT地址", "MQTT topic"]],
  ["b5exiCS2DqfscgWtCACz", ["新增行动配置", "Add Action Configuration"]],
  ["uvNfYK5zfOTRRPClzo21", ["请输入行动名称", "Enter Action Name"]],
  ["ip5CCP0h2lcVRY4281ns", ["请输入行动描述", "Enter Action Description"]],
  ["ueMSjnOmbZRrxIUEkWmO", ["端口", "Port"]],
  ["pJNIESuI13qwQ8Ifhp5p", ["请输入Token", "Please Enter Token"]],
  ["aEhbsEtazwSTN9TTL6fo", ["指令发送", "Command Sending"]],
  ["wUddVMoyzrz3ZObp79C6", ["消息通知", "Message Notification"]],
  ["q10gfiDrzFQmB1Mbwbqx", ["点位上线", "Point Online"]],
  ["dQwjU9UJ4v4CSoWdsR7E", ["点位离线", "Point Offline"]],
  ["hlbFgbkOSVZqBgfpaDAp", ["点位告警", "Alarm at Point"]],
  ["m8K7qYlJ3h4dSoFuwrHb", ["点位解警", "Alarm Cleared"]],
  ["ufIV8yMOw7RsWSqMxWPZ", ["无", "None"]],
  ["xThFKUQtwThEoonp3xPF", ["执行成功", "Execution Successful"]],
  ["yzC0q16eqDDwwmzwGauf", ["执行失败", "Execution failed"]],
  ["iFTIkijf77eHtoGOPFED", ["关联设备", "Add Component"]],
  ["lEVIi3opAvEy5JGRinBQ", ["展开", "Expand"]],
  ["xTIaKT8tNNaa9hT3gkx5", ["收起", "Collapse"]],
  ["cpIkmK2K3HFBYtRYA0Ky", ["模型配置", "Configuration Model"]],
  ["ip3jfunErDtNhhzQxZh4", ["配置通知", "Configuration Action"]],
  ["p5a0ZE4ww3YYgbWjpMmw", ["确认删除当前设备下所有部件?", "Comfirm to delete all components under the current Equipment?"]],
  ["aTRupk9I08nvDm3uD69l", ["部件数量", "Component Count"]],
  ["rFynVFQCVR087gmzBWMu", ["部件名", "Component Name"]],
  ["byGtrZRz0hegyYY8nPyi", ["监控设备数", "MonitoringEquipCount"]],
  ["wK09ChRRpxRh9Dkhyzhy", ["在线设备数", "OnlineEquipCount"]],
  ["rzgwgvUxMVVczdNwLdlf", ["离线设备数", "OfflineEquipCount"]],
  ["jTL0FgDnLNbsZgHPTknQ", ["异常设备数", "AlarmEquipCount"]],
  ["ztoJnkWAtmTDhy3UAGnq", ["监控部件数", "MonitoringComponentCount"]],
  ["u87FRaEWJ8U0JOjYG8jT", ["异常部件数", "AlarmComponentCount"]],
  ["yvjzD17VZHrQ6YX5cSAG", ["配置", "Setting"]],
  ["gSpwHmuSo8vMvZ0x0zvC", ["设备信息", "Equipment Info"]],
  ["tvXCdKeR8MFPs4djmfMm", ["设备", "Equipment"]],
  ["b8ZCAlgOyVDB6ufSEDr1", ["部件", "Component"]],
  ["fiyjrSFqk7eq8oOkyqW2", ["图片", "Image"]],
  ["cXn1I36qAH4RZPsqn838", ["数据关联", "Data association"]],
  ["k8gsEMsmrPsSpEp31SNl", ["生成预测性维护工单", "Work Orders"]],
  ["vQSmBr6q7yDsjeJYGvT5", ["选择", "Select"]],
  ["fqNvrVaKjzLIdb1dp3Vl", ["触发设置", "Trigger settings"]],
  ["ppML8UgEB2OOddeebBZX", ["数据类型", "DataType"]],
  ["achArCPt7iGIKxMRm4a0", ["数据来源", "dataSource"]],
  ["xHiILhybArs1hLah314v", ["存储形式", "storageType"]],
  ["f2flytjeE6QNcZdl9Whq", ["触发方式", "triggerMode"]],
  ["z1ghxywYOEjjH1IQx9Lq", ["推理频率（秒）", "triggerInterval"]],
  ["sZ77sBQP6NUtI7zuwE3O", ["运行配置", "Running Configuration"]],
  ["y5hZ3ZkGNaBKYJx9ynLQ", ["输入关联", "Input association"]],
  ["tBVIAm6jH1ib83fMQUwx", ["输入", "Input"]],
  ["rMUrIdnKR9RvcZV73QJS", ["时间", "Time"]],
  ["rOzqA1Y88SlUGPfr5zA8", ["模型输出", "Model Output"]],
  ["y3iDI1VgIrznVwxqe4IY", ["检测类型", "CheckType"]],
  ["wVVoQu9bXwAgQ329npqC", ["异常检测", "Anomaly detection"]],
  ["dhx4arnIlhkblj7JKLhC", ["故障分类检测", "Fault classification"]],
  ["n5PtbqM7YhXXVUiExSPN", ["剩余寿命预测", "Remaining Life Prediction"]],
  ["tjPzncg11yH3WCAsdu2z", ["是否保存当前部件模型数据", "Comfirm to save the current component model data"]],
  ["duWt33WfqjVTkyzTt8Ev", ["部件告警时动作", "Action when component alarm occurs"]],
  ["z2hHcX2hqMYmjnikmCnU", ["部件解警时动作", "Action during component alarm release"]],
  ["qTs3f6srs7mBdF9V1aBD", ["未处理", "Unhandled"]],
  ["hWTXvtT3ZDgMtVymR0EY", ["误判", "False Positive"]],
  ["ndRAAYLT3eZysp3qsi5A", ["无误", "Correct"]],
  ["cDt6fQLGPxUNN5cjrIhw", ["已处理", "Handled"]],
  ["bHuLcDb1ngUZTAJVOsRF", ["低频数据", "Low frequency data"]],
  ["vHiX0PXCExn6M8Qi2AwV", ["高频数据", "High frequency data"]],
  ["f56egQMq5QbS7gSBXZNw", ["AIOT", "EMB IoT Platform"]],
  ["p427Bg6fhmTCoHzB8YK6", ["时序数据库", "Time series database"]],
  ["zdK1TmohTFCMPO22BhDN", ["手动", "Hand movement"]],
  ["kqFitRpML32cEPpQv8iQ", ["自动", "Automatic"]],
  ["scXYP2JJtXLOO9wIyvd6", ["运行记录", "Inference records"]],
  ["eJDE405eyaEDmtz94UHY", ["查询日期", "Query Date"]],
  ["g23aYBLUcVuB8orMVcQs", ["开始时间", "Start Time"]],
  ["xtq85e0Gs4aSvjYn9uem", ["结束时间", "End Time"]],
  ["qRk2gNYEJzTamDq5whwh", ["推理结果", "Inference result"]],
  ["zSFNdR6bi9MrOg6FeKrL", ["处理结果", "Solve result"]],
  ["sZkCFknjjwUVl1FpDXTK", ["推理时间", "Inference Time"]],
  ["kQfmRMBGHORo5x2k9mdx", ["数据查看", "Data viewing"]],
  ["gN7yGhHGxZj9s7gGCtIQ", ["记录处理", "Record processing"]],
  ["pgX8jVL5Bc1gBUgdZFqx", ["处理成功", "Processing successful"]],
  ["bGmht76cZOVcIGQdFSQt", ["文件上传", "File Upload"]],
  ["sLiEqrFN5Qva52Pbavf5", ["数据分析", "Data analysis"]],
  ["qyKue9DePeivIEuI7fxN", ["实时值", "Real time value"]],
  ["lp1l40IEpbBEi6Rnq2KF", ["实时趋势", "Real Time Trends"]],
  ["vMOkQwOW7wtqL1KhRQie", ["相关性矩阵", "Correlation Matrix"]],
  ["d1FDMinLqZ0QPeyi4HFA", ["散点图", "Scatter"]],
  ["h0bPJDwjmbnlNx5on2eB", ["箱线图", "Boxplot"]],
  ["uCjaheJeDu9Rth9B8WBN", ["实时频谱", "Real time spectrum"]],
  ["qsJcdy0Q8yqLKLXL9IQu", ["筛选", "Search"]],
  ["dKlH6qzYQkoH8hATqa0m", ["请搜索设备名称", "Please search for equip name"]],
  ["cnLTzzqTBGRu8c7MVnfP", ["新建设备", "Create Equip"]],
  ["wq6XAhPExC1FO7CaxNnA", ["删除", "Delete"]],
  // ["seLJOHLX7ApEzNBM920x", ["", ""]],
  // ["dYEyq47W3LnOoSzsumAb", ["", ""]],
  // ["zyExGEF67fhXzhENPd7e", ["", ""]],
  // ["dxeSZZZIj3Kgpa8ye9g3", ["", ""]],
  // ["qpbVsgtjft9sscmYeilN", ["", ""]],
  // ["tkiCYRLVvlk2gjrXEpfX", ["", ""]],
  // ["jl3g6iuQwgdvy3ep3RJS", ["", ""]],
  // ["eVG38OdbsSwucW5vqAkO", ["", ""]],
  // ["vTe753iRlRDoemfgZLhc", ["", ""]],
  // ["xBVV64G2ApXVFIWMKZNY", ["", ""]],
  // ["ahm2WW2QAsRT7t9mHjO4", ["", ""]],
  // ["gtQ6CgAseVuqUwo2DYeT", ["", ""]],
  // ["z0J0auR8dSE6ym6DZQKt", ["", ""]],
  // ["hTR5h2RqAYMdTTbnLHu9", ["", ""]],
  // ["sbcjc0jFFUfOxuvJtq4J", ["", ""]],
  // ["tQl9eHTEoztEsOhSZvFi", ["", ""]],
  // ["tQxkL3FjzmFI0XvSez2m", ["", ""]],
  // ["e0uA6VSWMTvUqeHCcY9y", ["", ""]],
  // ["hM0bcJeLux1MEg6tX5im", ["", ""]],
  // ["fAZ2i3A0OlFhl2ygNRfu", ["", ""]],
  // ["jDyKy4VtNB9rb6NJ45xt", ["", ""]],
  // ["vZTsEiWFjbcnCXrf3Pg2", ["", ""]],
  // ["oyN6zYOUMZHq4rzdXrDK", ["", ""]],
  // ["sOT6HhCR9gEfzNlb9Jki", ["", ""]],
  // ["s4zyvTCDckzfZev9hq82", ["", ""]],
  // ["mSYm8utWvq0uCltMzlQB", ["", ""]],
  // ["rWIxQ6GF5M5TOgYY0HAA", ["", ""]],
  // ["ivJ0JZHuhqlQHZVJkSiF", ["", ""]],
  // ["dD9bhUw2MRGmsPjVMdFn", ["", ""]],
  // ["t6YUbHFpeC03O2RbWWCL", ["", ""]],
  // ["pvD6GiO0rwZEsWSWIMo3", ["", ""]],
  // ["bsqv0XR5q7yICj3Kxtkc", ["", ""]],
  // ["p6n8wAhmMmfAifqWuTFs", ["", ""]]
]
const m = new Map(arrs)
if (arrs.length !== m.size) {
  alert('Key重复了')
}
export default m

// ['', ['', '']],

// const a =
// [
//   ['安防烟火工厂误报', 'Security fireworks factory false alarm'],
//   ['安防烟火工厂漏报', 'Security fireworks factory missed reporting'],
//   ['安全帽工厂误报', 'Safety helmet factory false alarm'],
//   ['安全帽工厂漏报', 'Safety helmet factory missed reporting'],
//   ['通用人员检测工厂误报', 'General personnel detect factory false alarms'],
//   ['通用人员检测工厂漏报', 'General personnel detect factory missed reports'],
// ]
// const nanoid = (length = 20) => {
//   const chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
//   let result = chars[Math.floor(Math.random() * 26)] // 第一位为随机字母

//   for (let i = 1; i < length; i++) {
//     result += chars[Math.floor(Math.random() * chars.length)] // 其余位为随机字符
//   }
//   return result
// }

// let b = [], a = new Array(50).fill('')
// a.forEach(t => {
//   b.push(
//     [nanoid(), ['', '']]
//   )
// })

// JSON.stringify(b)
